### PR TITLE
v0.4.0 release

### PR DESCRIPTION
**Pull request by jjcarstens**

### CODE REVIEW

**Comment by fhunleth** [comment]
This looks good. My only comment is that it might be worth mentioning that if you have an existing device that you'll need to use the old upload.sh script and then switch to the new one for subsequent updates.

**Comment by jjcarstens** [comment]
I actually have been working on an `Upgrade to NervesSSH` section describing what to do. I want to place that in `nerves_ssh`, then link to it from this changelog (rather than include all the instructions in a large changelog block). What do you think about that?

**Comment by jjcarstens** [comment]
@fhunleth Updated with the upgrade notes

**Review by mobileoverlord — APPROVED** [review]
🎉

**Review by fhunleth — APPROVED** [review]

**Pull request merged**
