### PR TITLE
Remove automatic mdns_lite setup

### PR DESCRIPTION
**Pull request by fhunleth**
This wasn't documented and since we've removed all of the other
automatic configuration setup code, it seems consistent to remove this
too.

A nice side effect of this is that this project becomes a dependency and
documentation project. IMHO, it looks much more approachable than
`nerves_init_gadget` ever did when the time came for a project to move
beyond the defaults setup.

### CODE REVIEW

**Review by mobileoverlord — COMMENTED** [review]
I like this approach. More and more I am starting to dislike OTP application that start themselves. It feels like we should add some documentation around starting MDNS lite to the readme. The readme currently states

> mDNS, via MdnsLite. This supports nerves.local and the default hostname (i.e. nerves-1234.local) out of the box

**Comment by fhunleth** [comment]
Good point. That line of the docs needs to be updated. I'll take a pass later on that.

**Comment by fhunleth** [comment]
Updated.

**Comment by fhunleth** [comment]
@jsimmonds2 We're trying to work around https://github.com/elixir-lang/elixir/issues/10083. I'm really hoping that this fixes it.

**Review by mobileoverlord — APPROVED** [review]

**Review by ConnorRigby — APPROVED** [review]

**Review by jjcarstens — APPROVED** [review]

**Pull request merged**
